/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AtuBanda.java
 *
 * Created on 15/11/2015, 17:31:46
 */
package Telas;
import Conectividades.ConexaoBanda;
import javax.swing.JOptionPane;
import Estudio.Banda;

/**
 *
 * @author Rafa
 */
public class AtuBanda extends javax.swing.JFrame {

    /** Creates new form AtuBanda */
    public AtuBanda() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextId_Ban = new javax.swing.JTextField();
        jTextNome_Ban = new javax.swing.JTextField();
        jTextFone_Ban = new javax.swing.JTextField();
        jTextEmail_Ban = new javax.swing.JTextField();
        jTextGenero_Ban = new javax.swing.JTextField();
        jTextResponsavel_Ban = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextRua_Ban = new javax.swing.JTextField();
        jTextNumero_Ban = new javax.swing.JTextField();
        jButtonLimpar = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar Banda");
        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Atualizar Banda");

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/group2 (0).png"))); // NOI18N
        jLabel2.setText("Código");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/group2 (0).png"))); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/group2 (0).png"))); // NOI18N
        jLabel4.setText("Fone");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/group2 (0).png"))); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/group2 (0).png"))); // NOI18N
        jLabel6.setText("Genero");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/group2 (0).png"))); // NOI18N
        jLabel7.setText("Responsavel ");

        jTextId_Ban.setBackground(new java.awt.Color(204, 255, 255));

        jTextNome_Ban.setBackground(new java.awt.Color(204, 255, 255));
        jTextNome_Ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_BanActionPerformed(evt);
            }
        });

        jTextFone_Ban.setBackground(new java.awt.Color(204, 255, 255));
        jTextFone_Ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFone_BanActionPerformed(evt);
            }
        });

        jTextEmail_Ban.setBackground(new java.awt.Color(204, 255, 255));

        jTextGenero_Ban.setBackground(new java.awt.Color(204, 255, 255));

        jTextResponsavel_Ban.setBackground(new java.awt.Color(204, 255, 255));
        jTextResponsavel_Ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextResponsavel_BanActionPerformed(evt);
            }
        });

        jButtonBuscar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/Buscar/male226 (0).png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonAtualizar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/Atualizar/businessmen35 (0).png"))); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(204, 255, 255));
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/Excluir/teenager (0).png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonFechar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/Fechar/artist2 (0).png"))); // NOI18N
        jButtonFechar.setText("Fecahr");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/01_estudio_telas_menu.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/group2 (0).png"))); // NOI18N
        jLabel9.setText("Rua");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/group2 (0).png"))); // NOI18N
        jLabel10.setText("Numero");

        jTextRua_Ban.setBackground(new java.awt.Color(204, 255, 255));
        jTextRua_Ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRua_BanActionPerformed(evt);
            }
        });

        jTextNumero_Ban.setBackground(new java.awt.Color(204, 255, 255));

        jButtonLimpar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/Limpar/volume32 (0).png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5)))
                                            .addGap(29, 29, 29))
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jTextId_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jButtonBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextRua_Ban)
                                        .addComponent(jTextGenero_Ban)
                                        .addComponent(jTextEmail_Ban)
                                        .addComponent(jTextFone_Ban)
                                        .addComponent(jTextNome_Ban, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextNumero_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextResponsavel_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(jButtonAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))))
                .addGap(324, 324, 324))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextId_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNome_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addComponent(jTextFone_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jTextEmail_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextGenero_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextRua_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextResponsavel_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNumero_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jButtonAtualizar)
                .addGap(19, 19, 19)
                .addComponent(jButtonExcluir)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpar)
                .addGap(18, 18, 18)
                .addComponent(jButtonFechar)
                .addGap(210, 210, 210))
        );

        setBounds(350, 12, 619, 653);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        
        // Ação para buscar dados referente ao id
       
            try{
Banda banda = new Banda();
banda.setID_BAN(Integer.parseInt(jTextId_Ban.getText()));
ConexaoBanda conecta = new ConexaoBanda();
banda = conecta.buscarbanda(banda.getID_BAN());

if(banda.getID_BAN() != 0){
jTextNome_Ban.setText(banda.getNOME_BAN());
jTextFone_Ban.setText(banda.getFONE_BAN());
jTextEmail_Ban.setText(banda.getEMAIL_BAN());
jTextGenero_Ban.setText(banda.getGENERO_BAN());
jTextResponsavel_Ban.setText(banda.getRESPONSAVEL_BAN());
jTextRua_Ban.setText(banda.getRUA_BAN());
jTextNumero_Ban.setText(banda.getNUMERO_BAN());

jButtonAtualizar.setEnabled(true);
jButtonExcluir.setEnabled(true);
}else{
JOptionPane.showMessageDialog(null, "Cliente não encontrado","Aviso",
JOptionPane.ERROR_MESSAGE);
}
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, "Erro no banco de dados "+ex.getMessage(),
"Aviso",JOptionPane.ERROR_MESSAGE);
}
            
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new menu ().setVisible(true);
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // Açao para atualizar dados
        try{
int id_ban = Integer.parseInt(jTextId_Ban.getText());
String nome_ban = jTextNome_Ban.getText();
String fone_ban = jTextFone_Ban.getText();
String email_ban = jTextEmail_Ban.getText();
String genero_ban = jTextGenero_Ban.getText();
String responsavel_ban = jTextResponsavel_Ban.getText();
String rua_ban = jTextRua_Ban.getText();
String numero_ban = jTextNumero_Ban.getText();
Banda banda = new Banda(nome_ban, fone_ban, email_ban, genero_ban, responsavel_ban, rua_ban, numero_ban);
ConexaoBanda conecta_banda = new ConexaoBanda();
conecta_banda.AtualizarBanda(banda, id_ban);

jTextNome_Ban.setText("");
jTextFone_Ban.setText("");
jTextEmail_Ban.setText("");
jTextGenero_Ban.setText("");
jTextResponsavel_Ban.setText("");
jTextRua_Ban.setText("");
jTextNumero_Ban.setText("");

jTextId_Ban.requestFocus();

JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!","Aviso",
JOptionPane.INFORMATION_MESSAGE);
} catch(Exception ex){
JOptionPane.showMessageDialog(null, "Erro no banco de dados"+ex.getMessage(),"Aviso"
,JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // Açao para excluir dados
        try{
int id_ban = Integer.parseInt(jTextId_Ban.getText());
ConexaoBanda conecta_banda = new ConexaoBanda();
conecta_banda.RemoverBanda(id_ban);
jTextId_Ban.setText("");
jTextNome_Ban.setText("");
jTextFone_Ban.setText("");
jTextEmail_Ban.setText("");
jTextGenero_Ban.setText("");
jTextResponsavel_Ban.setText("");
jTextRua_Ban.setText("");
jTextNumero_Ban.setText("");
JOptionPane.showMessageDialog(null, "Dados removidos com sucesso!","Aviso",
JOptionPane.INFORMATION_MESSAGE);
}catch(Exception ex) {
JOptionPane.showMessageDialog(null, "Erro do banco de dados"+ex.getMessage(),"Aviso"
,JOptionPane.ERROR_MESSAGE);
ex.printStackTrace();

}
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextRua_BanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRua_BanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRua_BanActionPerformed

    private void jTextResponsavel_BanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextResponsavel_BanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextResponsavel_BanActionPerformed

    private void jTextNome_BanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_BanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_BanActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
jTextId_Ban.setText("");       
jTextNome_Ban.setText("");
jTextFone_Ban.setText("");
jTextEmail_Ban.setText("");
jTextGenero_Ban.setText("");
jTextResponsavel_Ban.setText("");
jTextRua_Ban.setText("");
jTextNumero_Ban.setText("");

jTextId_Ban.requestFocus();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTextFone_BanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFone_BanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFone_BanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtuBanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtuBanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtuBanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtuBanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AtuBanda().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextEmail_Ban;
    private javax.swing.JTextField jTextFone_Ban;
    private javax.swing.JTextField jTextGenero_Ban;
    private javax.swing.JTextField jTextId_Ban;
    private javax.swing.JTextField jTextNome_Ban;
    private javax.swing.JTextField jTextNumero_Ban;
    private javax.swing.JTextField jTextResponsavel_Ban;
    private javax.swing.JTextField jTextRua_Ban;
    // End of variables declaration//GEN-END:variables
}
