/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AtuInstrumento.java
 *
 * Created on 15/11/2015, 21:41:16
 */
package Telas;
import Conectividades.ConexaoInstrumento;
import javax.swing.JOptionPane;
import Estudio.Instrumento;


/**
 *
 * @author Rafa
 */
public class AtuInstrumento extends javax.swing.JFrame {

    /** Creates new form AtuInstrumento */
    public AtuInstrumento() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextId_Ins = new javax.swing.JTextField();
        jTextValor_Ins = new javax.swing.JTextField();
        jTextDescricao_Ins = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jFormattedTextFieldData_hora_saida_Ins = new javax.swing.JFormattedTextField();
        jFormattedTextFieldData_hora_retorno_Ins = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar Instruementos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Atualizar Instrumento");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/drummer3 (0).png"))); // NOI18N
        jLabel2.setText("Código");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/drummer3 (0).png"))); // NOI18N
        jLabel3.setText("Valor");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/drummer3 (0).png"))); // NOI18N
        jLabel4.setText("Descrição");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/drummer3 (0).png"))); // NOI18N
        jLabel5.setText("Data hora saida");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/drummer3 (0).png"))); // NOI18N
        jLabel6.setText("Data hora retorno");

        jTextId_Ins.setBackground(new java.awt.Color(204, 255, 255));

        jTextValor_Ins.setBackground(new java.awt.Color(204, 255, 255));

        jTextDescricao_Ins.setBackground(new java.awt.Color(204, 255, 255));

        jButtonBuscar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Buscar/orchestra6 (0).png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonAtualizar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Atualizar/musical147 (0).png"))); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(204, 255, 255));
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Excluir/triangle17 (0).png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonFechar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Fechar/vintage34 (0).png"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/01_estudio_telas_menu.png"))); // NOI18N

        jButtonLimpar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Limpar/saxophone7 (0).png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jFormattedTextFieldData_hora_saida_Ins.setBackground(new java.awt.Color(204, 255, 255));
        try {
            jFormattedTextFieldData_hora_saida_Ins.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####-##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jFormattedTextFieldData_hora_retorno_Ins.setBackground(new java.awt.Color(204, 255, 255));
        try {
            jFormattedTextFieldData_hora_retorno_Ins.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####-##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldData_hora_retorno_Ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldData_hora_retorno_InsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextId_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButtonBuscar))
                                .addComponent(jTextDescricao_Ins)
                                .addComponent(jTextValor_Ins))
                            .addComponent(jFormattedTextFieldData_hora_saida_Ins, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldData_hora_retorno_Ins, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAtualizar, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextId_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAtualizar)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonExcluir)
                        .addGap(25, 25, 25)
                        .addComponent(jButtonLimpar)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextValor_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDescricao_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jFormattedTextFieldData_hora_saida_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jFormattedTextFieldData_hora_retorno_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        setBounds(350, 12, 621, 653);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
         
        try{
Instrumento instrumento = new Instrumento();
instrumento.setID_INS(Integer.parseInt(jTextId_Ins.getText()));
ConexaoInstrumento conecta = new ConexaoInstrumento();
instrumento = conecta.buscarinstrumento(instrumento.getID_INS());

if(instrumento.getID_INS() != 0){
jTextValor_Ins.setText(instrumento.getVALOR_INS());
jTextDescricao_Ins.setText(instrumento.getDESCRICAO_INS());
jFormattedTextFieldData_hora_saida_Ins.setText(instrumento.getDATA_HORA_SAIDA_INS());
jFormattedTextFieldData_hora_retorno_Ins.setText(instrumento.getDATA_HORA_RETORNO_INS());


jButtonAtualizar.setEnabled(true);
jButtonExcluir.setEnabled(true);
}else{
JOptionPane.showMessageDialog(null, "Cliente não encontrado","Aviso",
JOptionPane.ERROR_MESSAGE);
}
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, "Erro no banco de dados "+ex.getMessage(),
"Aviso",JOptionPane.ERROR_MESSAGE);
}
            
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new menu ().setVisible(true);      
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
// TODO add your handling code here:
        
        try{
int id_Ins = Integer.parseInt(jTextId_Ins.getText());
ConexaoInstrumento conecta_Instrumento = new ConexaoInstrumento();
conecta_Instrumento.RemoverInstrumento(id_Ins);
jTextId_Ins.setText("");
jTextValor_Ins.setText("");
jTextDescricao_Ins.setText("");
jFormattedTextFieldData_hora_saida_Ins.setText("");
jFormattedTextFieldData_hora_retorno_Ins.setText("");
jTextId_Ins.requestFocus();

JOptionPane.showMessageDialog(null, "Dados removidos com sucesso!","Aviso",
JOptionPane.INFORMATION_MESSAGE);
}catch(Exception ex) {
JOptionPane.showMessageDialog(null, "Erro do banco de dados"+ex.getMessage(),"Aviso"
,JOptionPane.ERROR_MESSAGE);
ex.printStackTrace();

}        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
         try{
int Id_Ins = Integer.parseInt(jTextId_Ins.getText());
String valor_ins = jTextValor_Ins.getText();
String descricao_ins= jTextDescricao_Ins.getText();
String data_hora_saida_ins = jFormattedTextFieldData_hora_saida_Ins.getText();
String data_hora_retorno_ins = jFormattedTextFieldData_hora_retorno_Ins.getText();
Instrumento instrumento = new Instrumento(valor_ins, descricao_ins, data_hora_saida_ins, data_hora_retorno_ins);
ConexaoInstrumento conecta_instrumento = new ConexaoInstrumento();
conecta_instrumento.AtualizarInstrumento(instrumento, Id_Ins);

jTextId_Ins.setText("");
jTextValor_Ins.setText("");
jTextDescricao_Ins.setText("");
jFormattedTextFieldData_hora_saida_Ins.setText("");
jFormattedTextFieldData_hora_retorno_Ins.setText("");
jTextId_Ins.requestFocus();

JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!","Aviso",
JOptionPane.INFORMATION_MESSAGE);
} catch(Exception ex){
JOptionPane.showMessageDialog(null, "Erro no banco de dados"+ex.getMessage(),"Aviso"
,JOptionPane.ERROR_MESSAGE);
}
        
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:

jTextId_Ins.setText("");
jTextValor_Ins.setText("");
jTextDescricao_Ins.setText("");
jFormattedTextFieldData_hora_saida_Ins.setText("");
jFormattedTextFieldData_hora_retorno_Ins.setText("");
jTextId_Ins.requestFocus();
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jFormattedTextFieldData_hora_retorno_InsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldData_hora_retorno_InsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldData_hora_retorno_InsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtuInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtuInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtuInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtuInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AtuInstrumento().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JFormattedTextField jFormattedTextFieldData_hora_retorno_Ins;
    private javax.swing.JFormattedTextField jFormattedTextFieldData_hora_saida_Ins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextDescricao_Ins;
    private javax.swing.JTextField jTextId_Ins;
    private javax.swing.JTextField jTextValor_Ins;
    // End of variables declaration//GEN-END:variables
}
