/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AtuReserva_Gravacao.java
 *
 * Created on 15/11/2015, 22:12:08
 */
package Telas;
import Conectividades.ConexaoReserva_Gravacao;
import javax.swing.JOptionPane;
import Estudio.Reserva_Gravacao;


/**
 *
 * @author Rafa
 */
public class AtuReserva_Gravacao extends javax.swing.JFrame {

    /** Creates new form AtuReserva_Gravacao */
    public AtuReserva_Gravacao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextId_Reserva_Gra = new javax.swing.JTextField();
        jTextValor_Reserva_Gra = new javax.swing.JTextField();
        jTextData_Reserva_Gra = new javax.swing.JTextField();
        jTextHora_Entrada_Reserva_Gra = new javax.swing.JTextField();
        jTextHora_Saida_Reserva_Gra = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar Reserva Gravação");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Atualizar Reserva Gravação");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/headphones12 (0).png"))); // NOI18N
        jLabel2.setText("Código");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/headphones12 (0).png"))); // NOI18N
        jLabel3.setText("Valor");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/headphones12 (0).png"))); // NOI18N
        jLabel4.setText("Data");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/headphones12 (0).png"))); // NOI18N
        jLabel5.setText("Hora entrada");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/headphones12 (0).png"))); // NOI18N
        jLabel6.setText("Hora saida");

        jTextId_Reserva_Gra.setBackground(new java.awt.Color(204, 255, 255));

        jTextValor_Reserva_Gra.setBackground(new java.awt.Color(204, 255, 255));
        jTextValor_Reserva_Gra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValor_Reserva_GraActionPerformed(evt);
            }
        });

        jTextData_Reserva_Gra.setBackground(new java.awt.Color(204, 255, 255));
        jTextData_Reserva_Gra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextData_Reserva_GraActionPerformed(evt);
            }
        });

        jTextHora_Entrada_Reserva_Gra.setBackground(new java.awt.Color(204, 255, 255));

        jTextHora_Saida_Reserva_Gra.setBackground(new java.awt.Color(204, 255, 255));

        jButtonBuscar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/Buscar/business8 (0).png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonAtualizar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/Atualizar/music289 (0).png"))); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(204, 255, 255));
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/Excluir/headphones11 (0).png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonFechar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/Fechar/male97 (0).png"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/01_estudio_telas_menu.png"))); // NOI18N

        jButtonLimpar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/Limpar/sound13 (0).png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextId_Reserva_Gra, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(jButtonBuscar))
                            .addComponent(jTextHora_Saida_Reserva_Gra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jTextValor_Reserva_Gra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jTextHora_Entrada_Reserva_Gra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jTextData_Reserva_Gra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButtonAtualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButtonFechar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextId_Reserva_Gra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonBuscar))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextValor_Reserva_Gra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizar)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextData_Reserva_Gra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonExcluir)))
                .addGap(26, 26, 26)
                .addComponent(jButtonLimpar)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextHora_Entrada_Reserva_Gra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jButtonFechar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextHora_Saida_Reserva_Gra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        setBounds(350, 12, 619, 653);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextData_Reserva_GraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextData_Reserva_GraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextData_Reserva_GraActionPerformed

    private void jTextValor_Reserva_GraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValor_Reserva_GraActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextValor_Reserva_GraActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new menu ().setVisible(true);      
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        try{
int Id_Reserva_Gra = Integer.parseInt(jTextId_Reserva_Gra.getText());
ConexaoReserva_Gravacao conecta_Reserva_Gravacao = new ConexaoReserva_Gravacao();
conecta_Reserva_Gravacao.RemoverReserva_Gravacao( Id_Reserva_Gra);

jTextId_Reserva_Gra.setText("");
jTextValor_Reserva_Gra.setText("");
jTextData_Reserva_Gra.setText("");
jTextHora_Entrada_Reserva_Gra.setText("");
jTextHora_Saida_Reserva_Gra.setText("");
jTextId_Reserva_Gra.requestFocus();
        

JOptionPane.showMessageDialog(null, "Dados removidos com sucesso!","Aviso",
JOptionPane.INFORMATION_MESSAGE);
}catch(Exception ex) {
JOptionPane.showMessageDialog(null, "Erro do banco de dados"+ex.getMessage(),"Aviso"
,JOptionPane.ERROR_MESSAGE);
ex.printStackTrace();

}       
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        
        try{
int Id_Reserva_Gra = Integer.parseInt(jTextId_Reserva_Gra.getText());
String valor_reserva_gra = jTextValor_Reserva_Gra.getText();
String data_reserva_gra = jTextData_Reserva_Gra.getText();
String hora_entrada_reserva_gra = jTextHora_Entrada_Reserva_Gra.getText();
String hora_saida_reserva_gra = jTextHora_Saida_Reserva_Gra.getText();
Reserva_Gravacao reserva_gravacao = new Reserva_Gravacao(valor_reserva_gra, data_reserva_gra, hora_entrada_reserva_gra, hora_saida_reserva_gra);
ConexaoReserva_Gravacao conecta_Reserva_Gravacao = new ConexaoReserva_Gravacao();
conecta_Reserva_Gravacao.AtualizarReserva_Gravacao(reserva_gravacao, Id_Reserva_Gra);

jTextId_Reserva_Gra.setText("");
jTextValor_Reserva_Gra.setText("");
jTextData_Reserva_Gra.setText("");
jTextHora_Entrada_Reserva_Gra.setText("");
jTextHora_Saida_Reserva_Gra.setText("");
jTextId_Reserva_Gra.requestFocus();
        

JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!","Aviso",
JOptionPane.INFORMATION_MESSAGE);
} catch(Exception ex){
JOptionPane.showMessageDialog(null, "Erro no banco de dados"+ex.getMessage(),"Aviso"
,JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        
        try{
Reserva_Gravacao reserva_gravacao  = new Reserva_Gravacao();
reserva_gravacao .setID_RESERVA_GRA(Integer.parseInt(jTextId_Reserva_Gra .getText()));
ConexaoReserva_Gravacao conecta = new ConexaoReserva_Gravacao();
reserva_gravacao = conecta.buscarreserva_gravacao(reserva_gravacao.getID_RESERVA_GRA());

if(reserva_gravacao.getID_RESERVA_GRA() != 0){
jTextValor_Reserva_Gra.setText(reserva_gravacao.getVALOR_RESERVA_GRA());
jTextData_Reserva_Gra.setText(reserva_gravacao.getDATA_RESERVA_GRA());
jTextHora_Entrada_Reserva_Gra.setText(reserva_gravacao.getHORA_ENTRADA_RESERVA_GRA());
jTextHora_Saida_Reserva_Gra.setText(reserva_gravacao.getHORA_SAIDA_RESERVA_GRA());


jButtonAtualizar.setEnabled(true);
jButtonExcluir.setEnabled(true);
}else{
JOptionPane.showMessageDialog(null, "Cliente não encontrado","Aviso",
JOptionPane.ERROR_MESSAGE);
}
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, "Erro no banco de dados "+ex.getMessage(),
"Aviso",JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        
jTextId_Reserva_Gra.setText("");
jTextValor_Reserva_Gra.setText("");
jTextData_Reserva_Gra.setText("");
jTextHora_Entrada_Reserva_Gra.setText("");
jTextHora_Saida_Reserva_Gra.setText("");
jTextId_Reserva_Gra.requestFocus();
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtuReserva_Gravacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtuReserva_Gravacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtuReserva_Gravacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtuReserva_Gravacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AtuReserva_Gravacao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextData_Reserva_Gra;
    private javax.swing.JTextField jTextHora_Entrada_Reserva_Gra;
    private javax.swing.JTextField jTextHora_Saida_Reserva_Gra;
    private javax.swing.JTextField jTextId_Reserva_Gra;
    private javax.swing.JTextField jTextValor_Reserva_Gra;
    // End of variables declaration//GEN-END:variables
}
