/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AtuReserva_Ensaio.java
 *
 * Created on 15/11/2015, 21:11:27
 */
package Telas;
import Conectividades.ConexaoReserva_Ensaio;
import javax.swing.JOptionPane;
import Estudio.Reserva_Ensaio;


/**
 *
 * @author Rafa
 */
public class AtuReserva_Ensaio extends javax.swing.JFrame {

    /** Creates new form AtuReserva_Ensaio */
    public AtuReserva_Ensaio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextId_Reserva_Ens = new javax.swing.JTextField();
        jTextValor_Reserva_Ens = new javax.swing.JTextField();
        jTextData_Reserva_Ens = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jFormattedTextFieldHora_Entrada_Reserva_Ens = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHora_saida_Reserva_Ens = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar Reserva Enssaio");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Atualizar Reserva Ensaio");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/home78 (0).png"))); // NOI18N
        jLabel2.setText("Código");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/home78 (0).png"))); // NOI18N
        jLabel3.setText("Valor");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/home78 (0).png"))); // NOI18N
        jLabel4.setText("Data");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/home78 (0).png"))); // NOI18N
        jLabel5.setText("Hora entrada");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/home78 (0).png"))); // NOI18N
        jLabel6.setText("Hora saida");

        jTextId_Reserva_Ens.setBackground(new java.awt.Color(204, 255, 255));

        jTextValor_Reserva_Ens.setBackground(new java.awt.Color(204, 255, 255));

        jTextData_Reserva_Ens.setBackground(new java.awt.Color(204, 255, 255));

        jButtonBuscar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/Buscar/music note1 (0).png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonAtualizar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/Atualizar/song (0).png"))); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(204, 255, 255));
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/Excluir/fire34 (0).png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonFechar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/Fechar/music100 (0).png"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/01_estudio_telas_menu.png"))); // NOI18N

        jButtonLimpar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/Limpar/track6 (0).png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jFormattedTextFieldHora_Entrada_Reserva_Ens.setBackground(new java.awt.Color(204, 255, 255));
        try {
            jFormattedTextFieldHora_Entrada_Reserva_Ens.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jFormattedTextFieldHora_saida_Reserva_Ens.setBackground(new java.awt.Color(204, 255, 255));
        try {
            jFormattedTextFieldHora_saida_Reserva_Ens.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextId_Reserva_Ens, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButtonBuscar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFormattedTextFieldHora_saida_Reserva_Ens, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldHora_Entrada_Reserva_Ens, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jTextData_Reserva_Ens, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jTextValor_Reserva_Ens, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextId_Reserva_Ens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextValor_Reserva_Ens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizar)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextData_Reserva_Ens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonExcluir)))
                .addGap(20, 20, 20)
                .addComponent(jButtonLimpar)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextFieldHora_Entrada_Reserva_Ens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonFechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jFormattedTextFieldHora_saida_Reserva_Ens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        setBounds(350, 12, 619, 653);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        
         try{
Reserva_Ensaio reserva_ensaio = new Reserva_Ensaio();
reserva_ensaio.setID_RESERVA_ENS(Integer.parseInt(jTextId_Reserva_Ens.getText()));
ConexaoReserva_Ensaio conecta = new ConexaoReserva_Ensaio();
reserva_ensaio = conecta.buscarreserva_ensaio(reserva_ensaio.getID_RESERVA_ENS());

if(reserva_ensaio.getID_RESERVA_ENS() != 0){
jTextValor_Reserva_Ens.setText(reserva_ensaio.getVALOR_RESERVA_ENS());
jTextData_Reserva_Ens.setText(reserva_ensaio.getDATA_RESERVA_ENS());
jFormattedTextFieldHora_Entrada_Reserva_Ens.setText(reserva_ensaio.getHORA_ENTRADA_RESERVA_ENS());
jFormattedTextFieldHora_saida_Reserva_Ens.setText(reserva_ensaio.getHORA_SAIDA_RESERVA_ENS());


jButtonAtualizar.setEnabled(true);
jButtonExcluir.setEnabled(true);
}else{
JOptionPane.showMessageDialog(null, "Cliente não encontrado","Aviso",
JOptionPane.ERROR_MESSAGE);
}
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, "Erro no banco de dados "+ex.getMessage(),
"Aviso",JOptionPane.ERROR_MESSAGE);
}
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new menu ().setVisible(true);      
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        
        try{
int Id_Reserva_Ens = Integer.parseInt(jTextId_Reserva_Ens.getText());
ConexaoReserva_Ensaio conecta_Reserva_Ensaio = new ConexaoReserva_Ensaio();
conecta_Reserva_Ensaio.RemoverReserva_Ensaio(Id_Reserva_Ens);
jTextId_Reserva_Ens.setText("");
jTextValor_Reserva_Ens.setText("");
jTextData_Reserva_Ens.setText("");
jFormattedTextFieldHora_Entrada_Reserva_Ens.setText("");
jFormattedTextFieldHora_saida_Reserva_Ens.setText("");
jTextId_Reserva_Ens.requestFocus();

JOptionPane.showMessageDialog(null, "Dados removidos com sucesso!","Aviso",
JOptionPane.INFORMATION_MESSAGE);
}catch(Exception ex) {
JOptionPane.showMessageDialog(null, "Erro do banco de dados"+ex.getMessage(),"Aviso"
,JOptionPane.ERROR_MESSAGE);
ex.printStackTrace();

}        // TODO add
        
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        
jTextId_Reserva_Ens.setText("");
jTextValor_Reserva_Ens.setText("");
jTextData_Reserva_Ens.setText("");
jFormattedTextFieldHora_Entrada_Reserva_Ens.setText("");
jFormattedTextFieldHora_saida_Reserva_Ens.setText("");
jTextId_Reserva_Ens.requestFocus();
        
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        
        try{
int Id_Reserva_Ens = Integer.parseInt(jTextId_Reserva_Ens.getText());
String valor_reserva_ens = jTextValor_Reserva_Ens.getText();
String data_reserva_ens = jTextData_Reserva_Ens.getText();
String hora_entrada_reserva_ens = jFormattedTextFieldHora_Entrada_Reserva_Ens.getText();
String hora_saida_reserva_ens = jFormattedTextFieldHora_saida_Reserva_Ens.getText();
Reserva_Ensaio reserva_ensaio = new Reserva_Ensaio(valor_reserva_ens, data_reserva_ens, hora_entrada_reserva_ens, hora_saida_reserva_ens);
ConexaoReserva_Ensaio conecta_Reserva_Ensaio = new ConexaoReserva_Ensaio();
conecta_Reserva_Ensaio.AtualizarReserva_Ensaio(reserva_ensaio, Id_Reserva_Ens);

jTextId_Reserva_Ens.setText("");
jTextValor_Reserva_Ens.setText("");
jTextData_Reserva_Ens.setText("");
jFormattedTextFieldHora_Entrada_Reserva_Ens.setText("");
jFormattedTextFieldHora_saida_Reserva_Ens.setText("");
jTextId_Reserva_Ens.requestFocus();
        

JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!","Aviso",
JOptionPane.INFORMATION_MESSAGE);
} catch(Exception ex){
JOptionPane.showMessageDialog(null, "Erro no banco de dados"+ex.getMessage(),"Aviso"
,JOptionPane.ERROR_MESSAGE);
}
        
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtuReserva_Ensaio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtuReserva_Ensaio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtuReserva_Ensaio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtuReserva_Ensaio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AtuReserva_Ensaio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JFormattedTextField jFormattedTextFieldHora_Entrada_Reserva_Ens;
    private javax.swing.JFormattedTextField jFormattedTextFieldHora_saida_Reserva_Ens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextData_Reserva_Ens;
    private javax.swing.JTextField jTextId_Reserva_Ens;
    private javax.swing.JTextField jTextValor_Reserva_Ens;
    // End of variables declaration//GEN-END:variables
}
