/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadInstrumento.java
 *
 * Created on 15/11/2015, 21:28:04
 */
package Telas;
import Conectividades.ConexaoInstrumento;
import javax.swing.JOptionPane;
import Estudio.Instrumento;


/**
 *
 * @author Rafa
 */
public class CadInstrumento extends javax.swing.JFrame {

    /** Creates new form CadInstrumento */
    public CadInstrumento() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextValor_Ins = new javax.swing.JTextField();
        jTextDescricao_Ins = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jFTextField1Data_hora_saida_Ins = new javax.swing.JFormattedTextField();
        jFTextField1Data_hora_retorno_Ins = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Instrumento");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Cadastro de Instrumento");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/drummer3 (0).png"))); // NOI18N
        jLabel2.setText("Valor");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/drummer3 (0).png"))); // NOI18N
        jLabel3.setText("Descrição");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/drummer3 (0).png"))); // NOI18N
        jLabel4.setText("Data hora saida");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/drummer3 (0).png"))); // NOI18N
        jLabel5.setText("Data hora retorno ");

        jTextValor_Ins.setBackground(new java.awt.Color(204, 255, 255));

        jTextDescricao_Ins.setBackground(new java.awt.Color(204, 255, 255));
        jTextDescricao_Ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescricao_InsActionPerformed(evt);
            }
        });

        jButtonCadastrar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Cadastra/guitar33 (0).png"))); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonLimpar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Limpar/saxophone7 (0).png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonFechar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Fechar/vintage34 (0).png"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/01_estudio_telas_menu.png"))); // NOI18N

        jFTextField1Data_hora_saida_Ins.setBackground(new java.awt.Color(204, 255, 255));
        try {
            jFTextField1Data_hora_saida_Ins.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####-##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTextField1Data_hora_saida_Ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTextField1Data_hora_saida_InsActionPerformed(evt);
            }
        });

        jFTextField1Data_hora_retorno_Ins.setBackground(new java.awt.Color(204, 255, 255));
        try {
            jFTextField1Data_hora_retorno_Ins.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####-##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTextField1Data_hora_retorno_Ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTextField1Data_hora_retorno_InsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextValor_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jFTextField1Data_hora_retorno_Ins, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addComponent(jFTextField1Data_hora_saida_Ins, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addComponent(jTextDescricao_Ins, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jTextValor_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDescricao_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jFTextField1Data_hora_saida_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jFTextField1Data_hora_retorno_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButtonCadastrar)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonLimpar)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonFechar)))
                .addGap(141, 141, 141))
        );

        setBounds(350, 12, 619, 653);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDescricao_InsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescricao_InsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescricao_InsActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new menu ().setVisible(true);      
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        
        int id_ins = 0;
String valor_ins = jTextValor_Ins.getText();
String descricao_ins = jTextDescricao_Ins.getText();
String data_hora_saida_ins = jFTextField1Data_hora_saida_Ins.getText();
String data_hora_retorno_ins = jFTextField1Data_hora_retorno_Ins.getText();

try{
Instrumento instrumento = new Instrumento (id_ins, valor_ins, descricao_ins, data_hora_saida_ins, data_hora_retorno_ins);
ConexaoInstrumento conecta_instrumento = new ConexaoInstrumento();
conecta_instrumento.cadastrarInstrumento(instrumento);

jTextValor_Ins.setText("");
jTextDescricao_Ins.setText("");
jFTextField1Data_hora_saida_Ins.setText("");
jFTextField1Data_hora_retorno_Ins.setText("");
jTextValor_Ins.requestFocus();


JOptionPane.showMessageDialog(null,"Dados gragados com sucesso!","Aviso",JOptionPane.
INFORMATION_MESSAGE);
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, "Erro no banco de dados!"+ex.getMessage(),"Aviso",
JOptionPane.ERROR_MESSAGE);
ex.printStackTrace();
}
        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        
jTextValor_Ins.setText("");
jTextDescricao_Ins.setText("");
jFTextField1Data_hora_saida_Ins.setText("");
jFTextField1Data_hora_retorno_Ins.setText("");
jTextValor_Ins.requestFocus();

        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jFTextField1Data_hora_saida_InsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTextField1Data_hora_saida_InsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTextField1Data_hora_saida_InsActionPerformed

    private void jFTextField1Data_hora_retorno_InsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTextField1Data_hora_retorno_InsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTextField1Data_hora_retorno_InsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadInstrumento().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JFormattedTextField jFTextField1Data_hora_retorno_Ins;
    private javax.swing.JFormattedTextField jFTextField1Data_hora_saida_Ins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextDescricao_Ins;
    private javax.swing.JTextField jTextValor_Ins;
    // End of variables declaration//GEN-END:variables
}
