/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * menu.java
 *
 * Created on 15/11/2015, 14:48:24
 */
package Telas;

/**
 *
 * @author Rafa
 */
public class menu extends javax.swing.JFrame {

    /** Creates new form menu */
    public menu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton40 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBan = new javax.swing.JMenu();
        jMenuItemCadban = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAtuban = new javax.swing.JMenuItem();
        jMenuReservaens = new javax.swing.JMenu();
        jMenuItemCadreservaens = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAtureservaens = new javax.swing.JMenuItem();
        jMenuIns = new javax.swing.JMenu();
        jMenuItemCadins = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAtuins = new javax.swing.JMenuItem();
        jMenuReservagra = new javax.swing.JMenu();
        jMenuItemCadreservagra = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAtureservagra = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemTela_MenuPrincipal = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTela_Menu = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTela_CadBanda = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTela_AtuBanda = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTela_ReservaEnsaio = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTela_AtuReservaEnsaio = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTela_CadInstrumento = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTela_AtuInstrumento = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTela_CadReservaGravacao = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTela_AtuReservaGravacao = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu 01 Estúdio");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1586, 1122));

        jButton40.setBackground(new java.awt.Color(0, 0, 51));
        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/01-menu.png"))); // NOI18N
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        jMenuBan.setBackground(new java.awt.Color(51, 51, 255));
        jMenuBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/group2 (0).png"))); // NOI18N
        jMenuBan.setText("Banda");
        jMenuBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBanActionPerformed(evt);
            }
        });

        jMenuItemCadban.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        jMenuItemCadban.setBackground(new java.awt.Color(51, 51, 255));
        jMenuItemCadban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/Cadastra/leader (0).png"))); // NOI18N
        jMenuItemCadban.setText("Cadastrar");
        jMenuItemCadban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadbanActionPerformed(evt);
            }
        });
        jMenuBan.add(jMenuItemCadban);
        jMenuBan.add(jSeparator1);

        jMenuItemAtuban.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuItemAtuban.setBackground(new java.awt.Color(51, 51, 255));
        jMenuItemAtuban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/Atualizar/businessmen35 (0).png"))); // NOI18N
        jMenuItemAtuban.setText("Atualizar");
        jMenuItemAtuban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtubanActionPerformed(evt);
            }
        });
        jMenuBan.add(jMenuItemAtuban);

        jMenuBar1.add(jMenuBan);

        jMenuReservaens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/home78 (0).png"))); // NOI18N
        jMenuReservaens.setText("Reserva Ensaio");

        jMenuItemCadreservaens.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, 0));
        jMenuItemCadreservaens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/Cadastra/music191 (0).png"))); // NOI18N
        jMenuItemCadreservaens.setText("Cadastrar");
        jMenuItemCadreservaens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadreservaensActionPerformed(evt);
            }
        });
        jMenuReservaens.add(jMenuItemCadreservaens);
        jMenuReservaens.add(jSeparator4);

        jMenuItemAtureservaens.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, 0));
        jMenuItemAtureservaens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/Atualizar/song (0).png"))); // NOI18N
        jMenuItemAtureservaens.setText("Atualizar");
        jMenuItemAtureservaens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtureservaensActionPerformed(evt);
            }
        });
        jMenuReservaens.add(jMenuItemAtureservaens);

        jMenuBar1.add(jMenuReservaens);

        jMenuIns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/drummer3 (0).png"))); // NOI18N
        jMenuIns.setText("Instrumento");

        jMenuItemCadins.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, 0));
        jMenuItemCadins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Cadastra/guitar33 (0).png"))); // NOI18N
        jMenuItemCadins.setText("Cadastrar");
        jMenuItemCadins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadinsActionPerformed(evt);
            }
        });
        jMenuIns.add(jMenuItemCadins);
        jMenuIns.add(jSeparator5);

        jMenuItemAtuins.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, 0));
        jMenuItemAtuins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Atualizar/musical147 (0).png"))); // NOI18N
        jMenuItemAtuins.setText("Atualizar");
        jMenuItemAtuins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtuinsActionPerformed(evt);
            }
        });
        jMenuIns.add(jMenuItemAtuins);

        jMenuBar1.add(jMenuIns);

        jMenuReservagra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/headphones12 (0).png"))); // NOI18N
        jMenuReservagra.setText("Reserva Gravação");

        jMenuItemCadreservagra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, 0));
        jMenuItemCadreservagra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/Cadastra/notebook17 (0).png"))); // NOI18N
        jMenuItemCadreservagra.setText("Cadastrar");
        jMenuItemCadreservagra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadreservagraActionPerformed(evt);
            }
        });
        jMenuReservagra.add(jMenuItemCadreservagra);
        jMenuReservagra.add(jSeparator6);

        jMenuItemAtureservagra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        jMenuItemAtureservagra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/Atualizar/music289 (0).png"))); // NOI18N
        jMenuItemAtureservagra.setText("Atualizar");
        jMenuItemAtureservagra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtureservagraActionPerformed(evt);
            }
        });
        jMenuReservagra.add(jMenuItemAtureservagra);

        jMenuBar1.add(jMenuReservagra);

        jMenuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ajuda..png"))); // NOI18N
        jMenuAjuda.setText("Ajuda");
        jMenuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAjudaActionPerformed(evt);
            }
        });

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ajuda..png"))); // NOI18N
        jMenu2.setText("Ajuda");

        jMenuItemTela_MenuPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTela_MenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ajuda1.png"))); // NOI18N
        jMenuItemTela_MenuPrincipal.setText("Como usar tela Menu Principal");
        jMenuItemTela_MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTela_MenuPrincipalActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTela_MenuPrincipal);
        jMenu2.add(jSeparator3);

        jMenuItemTela_Menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTela_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ajuda1.png"))); // NOI18N
        jMenuItemTela_Menu.setText("Como usar tela Menu");
        jMenuItemTela_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTela_MenuActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTela_Menu);
        jMenu2.add(jSeparator7);

        jMenuItemTela_CadBanda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTela_CadBanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/Cadastra/leader (0).png"))); // NOI18N
        jMenuItemTela_CadBanda.setText("Como usar tela Cadastrar Banda");
        jMenuItemTela_CadBanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTela_CadBandaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTela_CadBanda);
        jMenu2.add(jSeparator8);

        jMenuItemTela_AtuBanda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTela_AtuBanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Banda/Atualizar/businessmen35 (0).png"))); // NOI18N
        jMenuItemTela_AtuBanda.setText("Como usar tela Atualizar Banda");
        jMenuItemTela_AtuBanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTela_AtuBandaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTela_AtuBanda);
        jMenu2.add(jSeparator9);

        jMenuItemTela_ReservaEnsaio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTela_ReservaEnsaio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/Cadastra/music191 (0).png"))); // NOI18N
        jMenuItemTela_ReservaEnsaio.setText("Como usar tela Cadastrar Reserva Ensaio");
        jMenuItemTela_ReservaEnsaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTela_ReservaEnsaioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTela_ReservaEnsaio);
        jMenu2.add(jSeparator10);

        jMenuItemTela_AtuReservaEnsaio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTela_AtuReservaEnsaio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Ensaio/Atualizar/song (0).png"))); // NOI18N
        jMenuItemTela_AtuReservaEnsaio.setText("Como usar tela Atualizar Reserva Ensaio");
        jMenuItemTela_AtuReservaEnsaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTela_AtuReservaEnsaioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTela_AtuReservaEnsaio);
        jMenu2.add(jSeparator11);

        jMenuItemTela_CadInstrumento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTela_CadInstrumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Cadastra/guitar33 (0).png"))); // NOI18N
        jMenuItemTela_CadInstrumento.setText("Como usar tela Cadastrar Instrumento");
        jMenuItemTela_CadInstrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTela_CadInstrumentoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTela_CadInstrumento);
        jMenu2.add(jSeparator12);

        jMenuItemTela_AtuInstrumento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTela_AtuInstrumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Instrumento/Atualizar/musical147 (0).png"))); // NOI18N
        jMenuItemTela_AtuInstrumento.setText("Como usar tela Atualizar Instrumeno");
        jMenuItemTela_AtuInstrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTela_AtuInstrumentoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTela_AtuInstrumento);
        jMenu2.add(jSeparator13);

        jMenuItemTela_CadReservaGravacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTela_CadReservaGravacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/Cadastra/notebook17 (0).png"))); // NOI18N
        jMenuItemTela_CadReservaGravacao.setText("Como usar tela Cadastrar Reserva Gravação");
        jMenuItemTela_CadReservaGravacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTela_CadReservaGravacaoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTela_CadReservaGravacao);
        jMenu2.add(jSeparator14);

        jMenuItemTela_AtuReservaGravacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTela_AtuReservaGravacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Gravação/Atualizar/music289 (0).png"))); // NOI18N
        jMenuItemTela_AtuReservaGravacao.setText("Como usar tela Atualizar Reserva Gravação");
        jMenuItemTela_AtuReservaGravacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTela_AtuReservaGravacaoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTela_AtuReservaGravacao);

        jMenuAjuda.add(jMenu2);
        jMenuAjuda.add(jSeparator2);

        jMenuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Final P.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar1.add(jMenuAjuda);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Sair/musical202 (0).png"))); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, 0));
        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Inco/Sair/musical202 (0).png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton40, javax.swing.GroupLayout.DEFAULT_SIZE, 1278, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton40, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1294)/2, (screenSize.height-738)/2, 1294, 738);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadbanActionPerformed
        // Acão para chamar a tela de cadastro de banda
       this.dispose();
        new CadBanda ().setVisible(true);
   
       
    }//GEN-LAST:event_jMenuItemCadbanActionPerformed

    private void jMenuItemAtubanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtubanActionPerformed
        // Acção para atualizar banda
         this.dispose();
         new AtuBanda ().setVisible(true);
            
    }//GEN-LAST:event_jMenuItemAtubanActionPerformed

    private void jMenuItemCadreservaensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadreservaensActionPerformed
        // Ação para cadastra reserva ensaio
        this.dispose();
        new CadReserva_Ensaio ().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadreservaensActionPerformed

    private void jMenuItemAtureservaensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtureservaensActionPerformed
        // Ação para atualizar reserva ensaio
        this.dispose();
        new AtuReserva_Ensaio ().setVisible(true);
    }//GEN-LAST:event_jMenuItemAtureservaensActionPerformed

    private void jMenuItemCadinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadinsActionPerformed
        // Ação para cadastrar instrumento
        this.dispose();
        new CadInstrumento ().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadinsActionPerformed

    private void jMenuItemAtuinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtuinsActionPerformed
        // Ação para atualizar instrumento
        this.dispose();
        new AtuInstrumento ().setVisible(true);
    }//GEN-LAST:event_jMenuItemAtuinsActionPerformed

    private void jMenuItemCadreservagraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadreservagraActionPerformed
        // Ação para cadastrar reserva gravação
        this.dispose();
        new CadReserva_Gravacao ().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadreservagraActionPerformed

    private void jMenuItemAtureservagraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtureservagraActionPerformed
        // Ação para atualizar reserva gravação
        this.dispose();
        new AtuReserva_Gravacao ().setVisible(true);
    }//GEN-LAST:event_jMenuItemAtureservagraActionPerformed

    private void jMenuBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBanActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jMenuBanActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
       this.dispose();
      new principal ().setVisible(true);
        
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jMenuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAjudaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuAjudaActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        // TODO add your handling code here:
        new Sobre ().setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemTela_MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTela_MenuPrincipalActionPerformed
        // Ação para setar tela que ensina usar menu principal.
        new Tela_MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_jMenuItemTela_MenuPrincipalActionPerformed

    private void jMenuItemTela_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTela_MenuActionPerformed
        // Ação para setar tela que ensina usar menu
        new Tela_Menu().setVisible(true);
    }//GEN-LAST:event_jMenuItemTela_MenuActionPerformed

    private void jMenuItemTela_CadBandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTela_CadBandaActionPerformed
        // Ação para setar tela que ensina usar cadastrar banda.
        new Tela_CadBanda().setVisible(true);
    }//GEN-LAST:event_jMenuItemTela_CadBandaActionPerformed

    private void jMenuItemTela_AtuBandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTela_AtuBandaActionPerformed
        // Ação para setar tela que ensina usar atualizar banda.
        new Tela_AtuBanda().setVisible(true);
    }//GEN-LAST:event_jMenuItemTela_AtuBandaActionPerformed

    private void jMenuItemTela_ReservaEnsaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTela_ReservaEnsaioActionPerformed
        // Ação para setar tela que ensina cadastrar reserva ensaio
        new Tela_ReservaEnsaio().setVisible(true);
    }//GEN-LAST:event_jMenuItemTela_ReservaEnsaioActionPerformed

    private void jMenuItemTela_AtuReservaEnsaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTela_AtuReservaEnsaioActionPerformed
        // Ação para setar a tela que ensina atualizar reserva ensaio.
        new Tela_AtuReservaEnsaio().setVisible(true);
    }//GEN-LAST:event_jMenuItemTela_AtuReservaEnsaioActionPerformed

    private void jMenuItemTela_CadInstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTela_CadInstrumentoActionPerformed
        // Ação para setar a tela que ensina cadastrar instrumento.
        new Tela_CadInstrumento().setVisible(true);
    }//GEN-LAST:event_jMenuItemTela_CadInstrumentoActionPerformed

    private void jMenuItemTela_AtuInstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTela_AtuInstrumentoActionPerformed
        // Ação para setar a tela que ensina atualizar instrumento.
        new Tela_AtuInstrumento().setVisible(true);
    }//GEN-LAST:event_jMenuItemTela_AtuInstrumentoActionPerformed

    private void jMenuItemTela_CadReservaGravacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTela_CadReservaGravacaoActionPerformed
        // Ação para setar a tela que ensina cadastrar reserva gravação.
        new Tela_CadReservaGravacao().setVisible(true);
    }//GEN-LAST:event_jMenuItemTela_CadReservaGravacaoActionPerformed

    private void jMenuItemTela_AtuReservaGravacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTela_AtuReservaGravacaoActionPerformed
        // Ação para setar a tela que ensina atualizar reserva gravação.
        new Tela_AtuReservaGravacao().setVisible(true);
    }//GEN-LAST:event_jMenuItemTela_AtuReservaGravacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton40;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuBan;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuIns;
    private javax.swing.JMenuItem jMenuItemAtuban;
    private javax.swing.JMenuItem jMenuItemAtuins;
    private javax.swing.JMenuItem jMenuItemAtureservaens;
    private javax.swing.JMenuItem jMenuItemAtureservagra;
    private javax.swing.JMenuItem jMenuItemCadban;
    private javax.swing.JMenuItem jMenuItemCadins;
    private javax.swing.JMenuItem jMenuItemCadreservaens;
    private javax.swing.JMenuItem jMenuItemCadreservagra;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemTela_AtuBanda;
    private javax.swing.JMenuItem jMenuItemTela_AtuInstrumento;
    private javax.swing.JMenuItem jMenuItemTela_AtuReservaEnsaio;
    private javax.swing.JMenuItem jMenuItemTela_AtuReservaGravacao;
    private javax.swing.JMenuItem jMenuItemTela_CadBanda;
    private javax.swing.JMenuItem jMenuItemTela_CadInstrumento;
    private javax.swing.JMenuItem jMenuItemTela_CadReservaGravacao;
    private javax.swing.JMenuItem jMenuItemTela_Menu;
    private javax.swing.JMenuItem jMenuItemTela_MenuPrincipal;
    private javax.swing.JMenuItem jMenuItemTela_ReservaEnsaio;
    private javax.swing.JMenu jMenuReservaens;
    private javax.swing.JMenu jMenuReservagra;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
